spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/nmapplicationTest?autoReconnect=true&useSSL=false
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: nmapplicationTest
    password: nmapplicationTest    
    hikari:      
      connection-test-query: select now()
      pool-name: springHikariCP  
  jackson:
    default-property-inclusion: non-null
  #File upload
  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
      location: /usr/src/NMAPP/nm-communication/meeting-Image/
logging:
  file:     
    name: /usr/src/NMAPP/nm-communication/nm-communication.log    
    max-history: 10        
  #pattern:
    #console: "%d %-5level %logger : %msg%n"
    #file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: trace