server:
  port: 8022
  servlet:    context-path: /communication
    
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/nmapplication?autoReconnect=true&useSSL=false
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: nmapplication
    password: nmapplication    
    hikari:      
      connection-test-query: select now()
      pool-name: springHikariCP  
  jackson:
    default-property-inclusion: non-null
  #File upload
  servlet:    multipart:      enabled: true
      max-request-size: 20MB      max-file-size: 5MB      location: D:/nmapp/fileupload/
logging:
  file:     
    name: D:/nmapp/nm-communication/nm-communication.log
    max-history: 10        
  #pattern:
    #console: "%d %-5level %logger : %msg%n"
    #file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: trace

#Push notification
app:
  firebase-configuration-file: google/testproject-deaf7-firebase-adminsdk-wfogz-11f49b8faf.json

keycloak:
  realm: nmapp
  auth-server-url: http://localhost:8020/auth
  bearer-only: true
  resource: nm-security
  security-constraints:
    - 
      authRoles:
        - SUPER-ADMIN
        - DISTRICT
        - MANDALAM
        - PANCHAYATH
        - MUNICIPALITY
        - WARD-INCHARGE      
      securityCollections:          
        - 
          name: meeting-schedule
          patterns: 
            - /create-meeting
            - /edit-meeting
            - /update-participants-attendance
            - /upload-file
            - /get-participants-list/*           
    - 
      authRoles:
        - SUPER-ADMIN
        - DISTRICT
        - MANDALAM
        - PANCHAYATH
        - MUNICIPALITY
        - WARD-INCHARGE
        - MEMBER      
      securityCollections:          
        - 
          name: view-meeting
          patterns: 
            - /get-meeting
            - /get-image-name-list
            - /get-image/*
            - /send-message                        