spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/nmapplicationTest?autoReconnect=true&useSSL=false
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: nmapplicationTest
    password: nmapplicationTest    
    hikari:      
      connection-test-query: select now()
      pool-name: springHikariCP  
  jackson:
    default-property-inclusion: non-null

master-realm-keyCloak:
  secret: 753d710a-1bf1-45a6-95ff-34bf4f592b39

logging:
  file:     
    name: /usr/src/NMAPP/nm-security/nm-security.log    
    max-history: 10        
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.nmsecurity: TRACE
    org.springframework.web: TRACE
    org.springframework.security: TRACE

  
    
     
   