server:
  port: 8021

  
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/nmapplication?autoReconnect=true&useSSL=false
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: nmapplication
    password: nmapplication    
    hikari:      
      connection-test-query: select now()
      pool-name: springHikariCP  
  jackson:
    default-property-inclusion: non-null
          
logging:
  file:     
    name: D:/nmapp/nm-campaigns-maintenance/nm-camp.log    
    max-history: 10        
  #pattern:
    #console: "%d %-5level %logger : %msg%n"
    #file: "%d %-5level [%thread] %logger : %msg%n"
  level:    org.springframework.web: trace

sms-api:
  base-uri: http://thesmsbuddy.com/api/v1/sms/send
  api-key:  WixiJ1LMzzPsIK0cjSOLM9gbFBzcmW7b
  type: 1
  sender-id: INFSMS
  flash: 0
   
keycloak:
  realm: nmapp
  auth-server-url: http://localhost:8020/auth
  bearer-only: true
  resource: nm-security
  security-constraints:
    - 
      authRoles:
        - SUPER-ADMIN
        - DISTRICT
        - MANDALAM
        - PANCHAYATH
        - MUNICIPALITY
        - WARD-INCHARGE
        - MEMBER
      securityCollections:          
        - 
          name: campaign-details
          patterns: 
            - /campaign/get-login-landing-info
            - /campaign/get-campaign-details
            - /campaign/collect-fund
            - /campaign/get-fund-collection-history/*
    -
      authRoles:
        - SUPER-ADMIN
        - DISTRICT
        - MANDALAM
        - PANCHAYATH
        - MUNICIPALITY
      securityCollections:
        -
          name: campaign-creation
          patterns:            - /campaign/create-campaign
          
    -
      authRoles:
         - SUPER-ADMIN
         - DISTRICT
      securityCollections:
        -
          name: campaign-status
          patterns:
            - /campaign/update-campaign-status/*