server:
  tomcat:
    remoteIpHeader: X-Forwarded-For
    protocolHeader: X-Forwarded-Proto
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak?autoReconnect=true&useSSL=false
    username: keycloak-user
    password: keycloak    
    hikari:      
      connection-test-query: select now()
      pool-name: springHikariCP
      
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: nm-admin
      password: nmpass
    realmImportFile: nmapp-realm-test.json
    
    
logging:
  file:     
    name: /usr/src/NMAPP/nm-auth/nm-auth.log    
    max-history: 10        
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.nmsecurity: TRACE
    org.springframework.web: TRACE
    org.springframework.security: TRACE
